# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='type',
            new_name='action_type',
        ),
    ]
