# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 23:37
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_image_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
