# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20170427_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='source',
            field=models.URLField(blank=True),
        ),
    ]
